### ISSUE TITLE
run error  vex/examples/simple_example.v

### ISSUE THREAD

**Issue by xiaojin20** [nedpals/vex#12]
error: redefinition of function `vex.ctx.send_404`

**Comment by nedpals** [comment]
@xiaojin20 V currently has problems when importing submodules

**Comment by xiaojin20** [comment]
新版本导入有问题，v旧版本，可以正常使用，是这样吗
There is a problem with the new version import, v the old version, can be used normally, is it true?

**Comment by nedpals** [comment]
@xiaojin20 It's true that the old version of V is more stable when it comes to importing. But there are lots of changes in Vex that takes advantage of the new syntax introduced in the new version.

**Comment by xiaojin20** [comment]
![Screenshot_20200518_100949_com termux](https://user-images.githubusercontent.com/62544875/82167888-bf299300-98ef-11ea-8a53-a891b71c745b.jpg)

**Comment by xiaojin20** [comment]
You, when will you update to the new vlang version,

**Comment by xiaojin20** [comment]
You, when will you update to the new vlang version,

**Comment by nedpals** [comment]
@xiaojin20 It's already using the features of the new V version :) It's just that the compiler importing submodules is broken

**Comment by xiaojin20** [comment]
你什么时候，修复这个问题呢

**Comment by xiaojin20** [comment]
When do you fix this problem

**Comment by nedpals** [comment]
@xiaojin20 Not sure when. I'm still exploring the compiler code

**Comment by xiaojin20** [comment]
ok，After repair, please inform, thank you

**Comment by nedpals** [comment]
@xiaojin20 Sure thing :smiley:

**Comment by xiaojin20** [comment]
In what version of vex, can it run normally!vlang0.1.13？

**Comment by harish2704** [comment]
@xiaojin20 : it seems like the vlang compiler fails to process duplicates in import statements and it can be quickly fixed shown in this command 

https://github.com/nedpals/vex/issues/17#issuecomment-763256034
