### ISSUE TITLE
db_example.v is not working

### ISSUE THREAD

**Issue by harish2704** [nedpals/vex#14]
Hi, 
I tried running the `db_example.v` provided in the example. It seems like it wont run as per the  spec of the vlang.
But , I was able to compile the `db_example.v` to C code, but the generated C code was not compiling to executable .

The problem is at the point of reffering `db` variable in  route handlers. For eg: [here](https://github.com/nedpals/vex/blob/d3c5b02e71e6980ce31c0affe7d5143db064db6a/examples/db_example.v#L57)

As per the documentation of Vlang,  functions are pure by default, thus, it can not use any variable defined outside of the function right? ( But still, I m surprised on the fact that,  V file compiled successfully to C code )

if that is the case, how we can expect this to work ?

( I manually edited the generated C code and made slight modifications to allow global variables, then C code successfully compiled and I was able to run the example. I seen the example in action. It was super cool. Thanks! )

**Comment by nedpals** [comment]
@harish2704 Hi. Vex and its examples hasn't been maintained and updated for a while. The DB example should've used the new built-in V SQL syntax for it. As for the pure functions, I'm not really sure about that.

**Comment by harish2704** [comment]
Thanks for pointing out the case of built-in V SQL syntax. I will check that.

Regarding pure functions: I didn't seen any documentation regarding "variable scope" or "function scope" in the vlang documentation. But it was clearly written that, global variables are not available in V. Thus, considering the fact that functions are pure in V by default,  I assumed that functions wont' be able to refer variables defined outside its scope.

**Comment by nedpals** [comment]
@harish2704 Regarding variable/function scope, they aren't implemented yet and closures are something that the team has discussed in our Discord server and will be implemented later as things getting stabilized.

**Comment by harish2704** [comment]
@nedpals : Wow! That is great news. Thanks for the update.

**Comment by harish2704** [comment]
db_example.v is now working after applying this simple patch specified here https://github.com/nedpals/vex/issues/17#issuecomment-763256034
