### ISSUE TITLE
Simple example does not working, has an error : cannot register struct `nedpals.vex.ctx.Req`, another type with this name exists

### ISSUE THREAD

**Issue by blackshirt** [nedpals/vex#23]
I'm doing simple learning vex, through examples provided in README file.
here the code i'm trying to learn 
```
import nedpals.vex.router
import nedpals.vex.ctx
import nedpals.vex.server

fn main() {
	mut router := route.new()
	router.route(.get, '/', fn (req &ctx.Req, mut res ctx.Resp) {
		res.send_file('index.html', 200)
	})
	server.serve(router, 6789)
}
```

i'm only have two files in my experiment folder, one is v file above, the other was html file.
```
$ ls 
index.html  main.v
```

when i'm trying to run `v run main.v`, i'm getting this error 
```
$ v run "/home/green/vexper/main.v"
/home/green/.vmodules/nedpals/vex/ctx/ctx.v:23:12: error: cannot register struct `nedpals.vex.ctx.Req`, another type with this name exists
   21 | 
   22 | // Server request data
   23 | pub struct Req {
      |            ~~~
   24 | pub mut:
   25 |     body      []byte
```
I dont know what happen really, and i think no other `Req` struct was defined before

Any helps very appreciated ...
Thanks for the time

**Comment by nedpals** [comment]
@blackshirt What version of V are you using? This happens when you are attempting to compile a Vex web app using an old version of V.

**Comment by blackshirt** [comment]
> @blackshirt What version of V are you using? This happens when you are attempting to compile a Vex web app using an old version of V.

Thanks for quick response, 
i think its a latest version, (but maybe i'm wrong)
this my V version
```
$ v version
V 0.2.1 0ca36aa
```

NB:
sorry, the latest version release was 0.2.2 ..i would update my v to the latest

**Comment by blackshirt** [comment]
thanks, i think its work now, but more silly question, this is about  'best way' to handle database connection in vex.
for the simpliciy, this code works for me ..
```
fn main() {
	
	mut app := router.new()
	db := sqlite.connect('db.sqlite3') or { panic(err) }
	c := url.CPool{db, true}
	app.inject(c)
	app.route(.get, '/', fn (req &ctx.Req, mut res ctx.Resp) {
	   res.send_file('index.html', 200)
	})
	app.route(.get, '/rups', fn (req &ctx.Req, mut res ctx.Resp) {
		db := &url.CPool(req.ctx)
		rows := db.rup_from_satker('63401')
		res.send_json<[]url.Rup>(rows, 200)
	})
	server.serve(app, 6789)
```
if i compared to builtin `vweb` module, i can initialize sqlite connection in `init_once`.
if i look at above code, i should initialize this `db := &url.CPool(req.ctx)` part for every route defined.

is there a clean way doing this ?
thanks

**Comment by nedpals** [comment]
@blackshirt closures aren't implemented yet and this is the only possible thing to do right now. We'll be improving this in the near future.

**Comment by nedpals** [comment]
vweb and Vex have different architectures so it isn't possible to just easily apply what vweb has accomplished.

**Comment by blackshirt** [comment]
> @blackshirt closures aren't implemented yet and this is the only possible thing to do right now. We'll be improving this in the near future.

okay, i see the problem ...
Thanks,
