### ISSUE TITLE
How can you use a value inside an anonymous handler function, if the value is define outside this handler

### ISSUE THREAD

**Issue by m41na** [nedpals/vex#43]
I have a situation like this

```
fn main() {
	//initialize the app
	mut app := router.new()
	mut repo := &TaskRepo{}

	app.route(.post, '/task', fn (req &ctx.Req, mut resp &ctx.Resp) {
		 create_new_task(&repo, req, resp)
	})
```

TaskRepo is a struct defined in another module and is imported into the main module. If I try to use it in the '/task' handler, I get a very clear error message that the 'repo' variable is not defined inside the handler.

```
.\main.v:46:21: error: undefined ident: `repo`
   44 |
   45 |     app.route(.post, '/task', fn (req &ctx.Req, mut resp &ctx.Resp) {
   46 |          create_new_task(&repo, req, resp)
      |                           ~~~~
   47 |     })
```

Is there a way around this? Let me know if my question is clear enough also

**Comment by nedpals** [comment]
@m41na Closures are not implemented at this moment. What you can do for now, is to use the `inject` method.

```v
fn main() {
	//initialize the app
	mut app := router.new()
	mut repo := &TaskRepo{}
        app.inject(repo)

	app.route(.post, '/task', fn (req &ctx.Req, mut resp &ctx.Resp) {
	         repo_from_ctx := &TaskRepo(req.ctx)
		 create_new_task(repo_from_ctx, req, resp)
	})
}
```

`app.inject` is just a "hack"/workaround to bypass this issue while thinking of other ways to pass values from the outside environment to the request handlers.

**Comment by m41na** [comment]
@nedpals Fantastic!! Your response cleared all my other lingering questions as well. Thank you very much, and yes, the 'hack' works nicely

**Comment by m41na** [comment]
The question was satisfactorily answered
