### ISSUE TITLE
cannot import module "http" (not found)

### ISSUE THREAD

**Issue by muraray** [nedpals/vex#7]
Platform: 
Linux a98277977ce1 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux

Running on a docker spec taken from 
https://github.com/taojy123/docker-vlang/blob/master/Dockerfile

V Version: V 0.1.24 c949e9e
VPM Version: vpm version 0.0.2

Any idea why am getting this "http"
Using one of the example from the https://github.com/nedpals/vex/blob/master/examples/simple_example.v

Am i missing something here?

`root@a98277977ce1:/code/blogy# v run server.v

/root/.vmodules/vex/server/server.v:8:5: cannot import module "http" (not found)
    6| import (
    7|  net
    8|  http
           ^
    9|  net.urllib
   10|  os

root@a98277977ce1:/code/blogy# `

Need your help.

**Comment by nedpals** [comment]
hi! as of now you can just change `http` to `net.http` and it will work fine. cant have fixes for now
